USE Inventory

SELECT * FROM begin_inventory
SELECT * FROM sales
SELECT * FROM end_inventory
SELECT * FROM purchase_prices
SELECT * FROM purchases

--1.What is the total sales revenue generated by each vendor?

SELECT
VendorNo,
VendorName,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue
FROM sales
GROUP BY
VendorNo,
VendorName
ORDER BY
TotalSalesRevenue DESC;

--2.What is the total purchase value for each vendor?

SELECT
VendorNumber,
VendorName,
ROUND(SUM(Dollars),2) AS TotalPurchaseValue
FROM purchases
GROUP BY
VendorNumber,
VendorName
ORDER BY
TotalPurchaseValue DESC;

--3.What is the total profit earned from each vendor?

SELECT
s.VendorNo,
s.VendorName,
ROUND(SUM(s.SalesDollars),2) AS TotalSalesRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.VendorNo,
s.VendorName
ORDER BY
TotalProfit DESC;

--4.Which vendors have the highest profit margins?

SELECT
s.VendorNo,
s.VendorName,
ROUND(SUM(s.SalesDollars),2) AS TotalSalesRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalProfit,
ROUND(((SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity))* 100.0) / SUM(s.SalesDollars), 2)
AS ProfitMarginPercentage
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.VendorNo,
s.VendorName
ORDER BY
ProfitMarginPercentage DESC;

--5.What percentage of total revenue is contributed by each vendor?

SELECT
VendorNo,
VendorName,
ROUND(SUM(SalesDollars),2) AS TotalRevenue,
ROUND(SUM(SalesDollars) * 100.0 /SUM(SUM(SalesDollars)) OVER (),2) 
AS RevenueContributionPercentage
FROM sales
GROUP BY
VendorNo,
VendorName
ORDER BY
RevenueContributionPercentage DESC;

--6.What percentage of total profit is contributed by each vendor?

SELECT
s.VendorNo,
s.VendorName,
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalProfit,
ROUND((SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity)) * 100.0 /
NULLIF(SUM(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity)) OVER (),0),2)
AS ProfitContributionPercentage
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.VendorNo,
s.VendorName
ORDER BY ProfitContributionPercentage DESC;

--7.Who are the top 10 vendors based on total sales revenue?

SELECT TOP 10
VendorNo,
VendorName,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue
FROM sales
GROUP BY
VendorNo,
VendorName
ORDER BY TotalSalesRevenue DESC;

--8.Who are the bottom 10 vendors based on total sales revenue?

SELECT TOP 10
VendorNo,
VendorName,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue
FROM sales
GROUP BY
VendorNo,
VendorName
ORDER BY TotalSalesRevenue ASC;

--9.Rank vendors using RANK().

SELECT
VendorNo,
VendorName,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue,
RANK() OVER(ORDER BY SUM(SalesDollars) DESC) AS VendorRank
FROM sales
GROUP BY
VendorNo,
VendorName
ORDER BY VendorRank;

--10.Rank vendors using DENSE_RANK().

SELECT
VendorNo,
VendorName,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue,
DENSE_RANK() OVER(ORDER BY SUM(SalesDollars) DESC) AS VendorRank
FROM sales
GROUP BY
VendorNo,
VendorName
ORDER BY VendorRank;

--11.What is the total sales revenue generated by each brand?

SELECT
Brand,
Description,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue
FROM sales
GROUP BY
Brand,
Description
ORDER BY TotalSalesRevenue DESC;

--12.What is the total profit earned by each brand?

SELECT
s.Brand,
s.Description,
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2)
AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.Brand,
s.Description
ORDER BY TotalProfit DESC;

--13.What is the current inventory value for each brand?

SELECT
Brand,
Description,
SUM(OnHand) AS CurrentInventory,
ROUND(SUM(OnHand * Price),2) AS InventoryValue
FROM end_inventory
GROUP BY
Brand,
Description
ORDER BY InventoryValue DESC;

--14.Which are the top 10 best-selling brands?

SELECT TOP 10
Brand,
Description,
SUM(SalesQuantity) AS TotalQuantitySold,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue
FROM sales
GROUP BY
Brand,
Description
ORDER BY TotalQuantitySold DESC;

--15.Which are the bottom 10 least-selling brands?

SELECT TOP 10
Brand,
Description,
SUM(SalesQuantity) AS TotalQuantitySold,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue
FROM sales
GROUP BY
Brand,
Description
ORDER BY TotalQuantitySold ASC;

--16.Which brands generate the highest profit?

SELECT TOP 10
s.Brand,
s.Description,
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2)
AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.Brand,
s.Description
ORDER BY TotalProfit DESC;

--17.Which brands generate the lowest profit?

SELECT TOP 10
s.Brand,
s.Description,
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2)
AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.Brand,
s.Description
ORDER BY TotalProfit ASC;

--18.What is the profit margin for each brand?

SELECT
s.Brand,
s.Description,
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalProfit,
ROUND((SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity)) * 100.0 
/NULLIF(SUM(s.SalesDollars),0),2)
AS ProfitMarginPercentage
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
s.Brand,
s.Description
ORDER BY ProfitMarginPercentage DESC;

--19.What percentage of total revenue is contributed by each brand?

SELECT
Brand,
Description,
ROUND(SUM(SalesDollars),2) AS TotalRevenue,
ROUND(SUM(SalesDollars) * 100.0 /SUM(SUM(SalesDollars)) OVER (),2)
AS RevenueContributionPercentage
FROM sales
GROUP BY
Brand,
Description
ORDER BY RevenueContributionPercentage DESC;

--20.Rank brands based on sales revenue.

SELECT
Brand,
Description,
ROUND(SUM(SalesDollars),2) AS TotalSalesRevenue,
RANK() OVER(ORDER BY SUM(SalesDollars) DESC) AS BrandRank
FROM sales
GROUP BY
Brand,
Description
ORDER BY BrandRank;

--21.What is the average purchase quantity?

SELECT
ROUND(AVG(CAST(Quantity AS FLOAT)),2) AS AveragePurchaseQuantity
FROM purchases;

--22.What is the average purchase price per unit?

SELECT
ROUND(AVG(PurchasePrice),2) AS AveragePurchasePrice
FROM purchases;

--23.What is the total purchase value?

SELECT
ROUND(SUM(Dollars),2) AS TotalPurchaseValue
FROM purchases;

--24.How much quantity has been purchased from each vendor?

SELECT
VendorNumber,
VendorName,
SUM(Quantity) AS TotalQuantityPurchased,
ROUND(SUM(Dollars),2) AS TotalPurchaseValue
FROM purchases
GROUP BY
VendorNumber,
VendorName
ORDER BY TotalQuantityPurchased DESC;

--25.Which products are purchased in the largest quantities?

SELECT TOP 10
Brand,
Description,
SUM(Quantity) AS TotalQuantityPurchased,
ROUND(SUM(Dollars),2) AS TotalPurchaseValue
FROM purchases
GROUP BY
Brand,
Description
ORDER BY TotalQuantityPurchased DESC;

--26.How does purchase quantity relate to unit purchase price?

SELECT
Brand,
Description,
SUM(Quantity) AS TotalQuantityPurchased,
ROUND(AVG(PurchasePrice),2) AS AveragePurchasePrice
FROM purchases
GROUP BY
Brand,
Description
ORDER BY TotalQuantityPurchased DESC;

--27.Which purchase transactions have the highest purchase value?

SELECT TOP 10
PONumber,
VendorNumber,
VendorName,
Brand,
Description,
Quantity,
ROUND(PurchasePrice,2) AS PurchasePrice,
ROUND(Dollars,2) AS PurchaseValue
FROM purchases
ORDER BY Dollars DESC;

--28.Which vendors offer the lowest average purchase prices?

SELECT TOP 10
VendorNumber,
VendorName,
ROUND(AVG(PurchasePrice),2) AS AveragePurchasePrice
FROM purchases
GROUP BY
VendorNumber,
VendorName
ORDER BY AveragePurchasePrice ASC;

--29.Which vendors offer the highest average purchase prices?

SELECT TOP 10
VendorNumber,
VendorName,
ROUND(AVG(PurchasePrice),2) AS AveragePurchasePrice
FROM purchases
GROUP BY
VendorNumber,
VendorName
ORDER BY AveragePurchasePrice DESC;

--30.What is the current inventory quantity?

SELECT
SUM(OnHand) AS CurrentInventoryQuantity,
ROUND(SUM(OnHand * Price),2) AS CurrentInventoryValue
FROM end_inventory;

--31.What is the current inventory value?

SELECT
ROUND(SUM(OnHand * Price),2) AS TotalInventoryValue
FROM end_inventory;

--32.What is the inventory turnover ratio by brand?

SELECT
b.Brand,
b.Description,
SUM(s.SalesQuantity) AS TotalSalesQuantity,
ROUND(AVG((b.OnHand + e.OnHand) / 2.0),2) AS AverageInventory,
ROUND(SUM(s.SalesQuantity) /NULLIF(AVG((b.OnHand + e.OnHand) / 2.0),0),2)
AS InventoryTurnover
FROM begin_inventory AS b
INNER JOIN end_inventory AS e
ON b.InventoryId = e.InventoryId
INNER JOIN sales AS s
ON b.InventoryId = s.InventoryId
GROUP BY
b.Brand,
b.Description
ORDER BY InventoryTurnover DESC;

--33.Which inventory items are slow moving?

SELECT
e.Brand,
e.Description,
SUM(e.OnHand) AS CurrentStock,
SUM(ISNULL(s.SalesQuantity,0)) AS TotalSalesQuantity
FROM end_inventory AS e
LEFT JOIN sales AS s
ON e.InventoryId = s.InventoryId
GROUP BY
e.Brand,
e.Description
HAVING SUM(ISNULL(s.SalesQuantity,0)) < 100
ORDER BY TotalSalesQuantity;

--34.Which inventory items can be classified as dead stock?

SELECT
e.Brand,
e.Description,
SUM(e.OnHand) AS CurrentStock,
SUM(ISNULL(s.SalesQuantity,0)) AS TotalSalesQuantity
FROM end_inventory AS e
LEFT JOIN sales AS s
ON e.InventoryId = s.InventoryId
GROUP BY
e.Brand,
e.Description
HAVING
SUM(ISNULL(s.SalesQuantity,0)) = 0
AND SUM(e.OnHand) > 0
ORDER BY CurrentStock DESC;

--35.How much capital is locked in inventory?

SELECT
ROUND(SUM(OnHand * Price),2) AS CapitalLockedInInventory
FROM end_inventory;

--36.What is the inventory quantity and value by vendor?

SELECT
pp.VendorNumber,
pp.VendorName,
SUM(e.OnHand) AS CurrentInventory,
ROUND(SUM(e.OnHand * e.Price),2) AS InventoryValue
FROM end_inventory AS e
INNER JOIN purchase_prices AS pp
ON e.Brand = pp.Brand
AND e.Description = pp.Description
AND e.Size = pp.Size
GROUP BY
pp.VendorNumber,
pp.VendorName
ORDER BY InventoryValue DESC;

--37.What is the inventory quantity and value by brand?

SELECT
Brand,
Description,
SUM(OnHand) AS CurrentInventory,
ROUND(SUM(OnHand * Price),2) AS InventoryValue
FROM end_inventory
GROUP BY
Brand,
Description
ORDER BY InventoryValue DESC;

--38.What is the average Days Inventory Outstanding?

SELECT
ROUND((AVG((b.OnHand + e.OnHand) / 2.0) /
NULLIF(SUM(pp.PurchasePrice * s.SalesQuantity),0)) * 365,2)
AS DaysInventoryOutstanding
FROM begin_inventory AS b
INNER JOIN end_inventory AS e
ON b.InventoryId = e.InventoryId
INNER JOIN sales AS s
ON b.InventoryId = s.InventoryId
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size;

--39.What is the monthly sales trend?

SELECT
YEAR(SalesDate) AS SalesYear,
MONTH(SalesDate) AS SalesMonth,
ROUND(SUM(SalesDollars),2) AS TotalSales
FROM sales
GROUP BY
YEAR(SalesDate),
MONTH(SalesDate)
ORDER BY
SalesYear,
SalesMonth;

--40.What is the monthly profit trend?

SELECT
YEAR(s.SalesDate) AS SalesYear,
MONTH(s.SalesDate) AS SalesMonth,
ROUND(SUM(s.SalesDollars) -SUM(pp.PurchasePrice * s.SalesQuantity),2)
AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
YEAR(s.SalesDate),
MONTH(s.SalesDate)
ORDER BY
SalesYear,SalesMonth;

--41.What is the monthly purchase trend?

SELECT
YEAR(PODate) AS PurchaseYear,
MONTH(PODate) AS PurchaseMonth,
ROUND(SUM(Dollars),2) AS TotalPurchaseValue
FROM purchases
GROUP BY
YEAR(PODate),
MONTH(PODate)
ORDER BY
PurchaseYear,
PurchaseMonth;

--42.What is the company's total gross profit?

SELECT
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2) AS GrossProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size;

--43.What is the overall gross profit margin?

SELECT
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(pp.PurchasePrice * s.SalesQuantity),2) AS TotalPurchaseCost,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2) AS GrossProfit,
ROUND((SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity)) * 100.0 /
NULLIF(SUM(s.SalesDollars),0),2)
AS GrossProfitMargin
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size;

--44.What is the cumulative sales revenue over time?

SELECT
SalesDate,
ROUND(SUM(SalesDollars),2) AS DailySales,
ROUND(
SUM(SUM(SalesDollars)) OVER(ORDER BY SalesDate),2) AS RunningRevenue
FROM sales
GROUP BY SalesDate
ORDER BY SalesDate;

--45.What is the cumulative profit over time?

SELECT
s.SalesDate,
ROUND(SUM(s.SalesDollars) -SUM(pp.PurchasePrice * s.SalesQuantity),2) AS DailyProfit,
ROUND(SUM(SUM(s.SalesDollars) -
SUM(pp.PurchasePrice * s.SalesQuantity)) OVER(ORDER BY s.SalesDate),2) AS RunningProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY s.SalesDate
ORDER BY s.SalesDate;

--46.Compare monthly revenue and profit.

SELECT
YEAR(s.SalesDate) AS SalesYear,
MONTH(s.SalesDate) AS SalesMonth,
ROUND(SUM(s.SalesDollars),2) AS TotalRevenue,
ROUND(SUM(s.SalesDollars) - SUM(pp.PurchasePrice * s.SalesQuantity),2)
AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
YEAR(s.SalesDate),
MONTH(s.SalesDate)
ORDER BY
SalesYear,
SalesMonth;

--47.Calculate month-over-month sales growth using LAG().

WITH MonthlySales AS
(SELECT
YEAR(SalesDate) AS SalesYear,
MONTH(SalesDate) AS SalesMonth,
ROUND(SUM(SalesDollars),2) AS TotalSales
FROM sales
GROUP BY
YEAR(SalesDate),
MONTH(SalesDate))
SELECT
SalesYear,
SalesMonth,
TotalSales,
LAG(TotalSales) OVER(ORDER BY SalesYear, SalesMonth) AS PreviousMonthSales,
ROUND((TotalSales - LAG(TotalSales) OVER(ORDER BY SalesYear, SalesMonth)) * 100.0
/NULLIF(LAG(TotalSales) OVER(ORDER BY SalesYear, SalesMonth),0),2)
AS MonthlyGrowthPercentage
FROM MonthlySales
ORDER BY
SalesYear,
SalesMonth;

--48.Calculate month-over-month profit growth using LAG().

WITH MonthlyProfit AS
(SELECT
YEAR(s.SalesDate) AS SalesYear,
MONTH(s.SalesDate) AS SalesMonth,
ROUND(SUM(s.SalesDollars) -SUM(pp.PurchasePrice * s.SalesQuantity),2)
AS TotalProfit
FROM sales AS s
INNER JOIN purchase_prices AS pp
ON s.Brand = pp.Brand
AND s.Description = pp.Description
AND s.Size = pp.Size
GROUP BY
YEAR(s.SalesDate),
MONTH(s.SalesDate)
)
SELECT
SalesYear,
SalesMonth,
TotalProfit,
LAG(TotalProfit) OVER(ORDER BY SalesYear, SalesMonth) AS PreviousMonthProfit,
ROUND((TotalProfit -LAG(TotalProfit) OVER(ORDER BY SalesYear, SalesMonth)) * 100.0
/ NULLIF(LAG(TotalProfit) OVER(ORDER BY SalesYear, SalesMonth),0),2)
AS MonthlyProfitGrowthPercentage
FROM MonthlyProfit
ORDER BY
SalesYear,
SalesMonth;

--TOTAL PROFIT

SELECT
s.VendorNo,
s.VendorName,
SUM(s.SalesDollars) AS TotalSales,
SUM(s.SalesQuantity * p.PurchasePrice) AS TotalCost,
ROUND(SUM(s.SalesDollars - (s.SalesQuantity * p.PurchasePrice)),2) AS TotalProfit
FROM sales s
JOIN purchase_prices p
ON s.Brand = p.Brand
AND s.Description = p.Description
AND s.Size = p.Size
GROUP BY
s.VendorNo,
s.VendorName;